"""add album likes

Revision ID: 49c2efd600f3
Revises: d043b3ccb6fc
Create Date: 2026-09-19 09:20:31.041145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c2efd600f3'
down_revision: Union[str, Sequence[str], None] = 'd043b3ccb6fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_likes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('album_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'album_id')
    )
    op.add_column('albums', sa.Column('likes_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'likes_count')
    op.drop_table('album_likes')
    # ### end Alembic commands ###
