"""Add embedding and is_public to albums

Revision ID: d043b3ccb6fc
Revises: 9dad654470ce
Create Date: 2026-09-19 08:57:06.324232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd043b3ccb6fc'
down_revision: Union[str, Sequence[str], None] = '9dad654470ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'embedding')
    # ### end Alembic commands ###
